appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: lMUEPNQHiDKayK7D5bg+sRzMJdeE1p7X30zRQGWY8LRMtmxjgUbU+Djh+TdKbqbQOJvlSPFPNOINKbi1ZGO+dzt8tulsXiH59s74C5/+iCvhBTydrFz/QvM9keDnMksU8UKJM2qQH3ejJJPGT3h4jGalYcH1QKQETcGdX9TGnNNS8WD3jb4uW5TjTLTNgRq9vkzhhaFC+jv+iRpItTnLR90ZJvopF+4AjZixxTHAImk6gKARwdyWihpJoC+Ut/LCBUCmqvr9bfe0AwIRU1xdYf9bw56VvNRU6ylNZxT8Rz3oZVmgj7TT5rqduTXDLwgqpgSwNDALKY6lc6iIoTWps4pd5jd/ZOvwYOL2rVcAM3DJ5TfaDTDaEu8cFrKS0dwiAtHyF+lDEoeyZQt7zf1Ksr/wpHyaAygAabO+g7c53w+K4CSJuUwc7dUHoZBaV2YltVZtYkl+WGhnVdQRMtJADFAGx8ggEosie3OOQCvjaGAO5py4F1RsELpxhzcoQCw6S8/VinkQwinHTeAUZZcsOtWpTopf10VTd1GlUUtxYFt3q/F9SOLU2gm+3cx3z4BJFlJT/xoXVDpz+8+eWrpYmQd50oMPwp3/UwvpiCR1KPhvzq5fvCxaphMUukk8RmOmxPDaGcvkQvQI8eQvd6s95kLDDiIQ+V7xEjGf6M8GUus=}
